# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dry-validation'
gem 'ferrum'
gem 'puma'
gem 'rackup'
gem 'sinatra'

group :development do
  gem 'rubocop', require: false
  gem 'ruby-lsp', require: false
end
